name: Tweet "Yukari Takeba"

on:
  schedule:
    - cron: '0 16 * * *'  # Runs every day at 12:00 EDT
  workflow_dispatch:

jobs:
  tweet:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install tweepy
      run: pip install tweepy

    - name: Run tweet script
      env:
        API_KEY: ${{ secrets.API_KEY }}
        API_KEY_SECRET: ${{ secrets.API_KEY_SECRET }}
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
      run: python tweet.py
