name: Daily Yukari Takeba Tweet

on:
  schedule:
    - cron: '0 17 * * *'  # 12 PM EDT / 17:00 UTC
  workflow_dispatch:

jobs:
  tweet:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}  # ✅ Use PAT so Git can push

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install tweepy
        run: pip install tweepy

      - name: Run tweet script
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_KEY_SECRET: ${{ secrets.API_KEY_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        run: python tweet.py

      - name: Commit daycount update
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config user.name "fuukdle"
          git config user.email "fuukdlewebsite@gmail.com"

          # Authenticate using PAT
          git remote set-url origin https://x-access-token:${PAT_TOKEN}@github.com/fuukdle/takebot

          # ✅ Stage and commit FIRST to avoid rebase issues
          git add daycount.txt
          git commit -m "Increment daycount" || echo "No changes to commit"

          # ✅ Now safe to pull
          git pull --rebase

          # ✅ Push the committed update
          git push origin HEAD:main
