name: Tweet "Yukari Takeba"

on:
  schedule:
    - cron: '0 12 * * *'  # Every day at 12:00 UTC
  workflow_dispatch:

jobs:
  tweet:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install requests
      run: pip install requests

    - name: Run tweet script
      env:
        BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
      run: python tweet.py
